# IMPORTING ALL LIBRARIES

In [16]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder,StandardScaler,OneHotEncoder
import pickle

In [17]:
#loading the data
data=pd.read_csv('../data/Churn_Modelling.csv')

In [18]:
#First view of data
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [19]:
data=data.drop(columns=['RowNumber','CustomerId','Surname'])

In [20]:
#label encoding 
le_gen=LabelEncoder()
data['Gender']=le_gen.fit_transform(data['Gender'])

In [21]:
#Onehot
onehot_geo=OneHotEncoder(handle_unknown='ignore')
geo_encoded=onehot_geo.fit_transform(data[['Geography']]).toarray()
geo_encoded_df=pd.DataFrame(geo_encoded,columns=onehot_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [22]:
data=pd.concat([data.drop('Geography',axis=1),geo_encoded_df],axis=1)

In [23]:
x=data.drop(['EstimatedSalary'],axis=1)

In [24]:
y=data['EstimatedSalary']

In [25]:
x.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,0,0.0,0.0,1.0

#### Train test split

In [29]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=42)

In [30]:
#scaling the datan
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)

In [31]:
#saving the processed encoder and scaled data
with open('le_gen.pkl','wb') as file:
    pickle.dump(le_gen,file)

with open('onehot_geo.pkl','wb') as file:
    pickle.dump(onehot_geo,file)

with open('scaler.pkl','wb') as file:
    pickle.dump(scaler,file)

# ANN Regression Problem statement

In [32]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [37]:
model=Sequential([
    Dense(64,activation='relu',input_shape=(x_train.shape[1],)),
    Dense(32,activation='relu'),
    Dense(1) #linear activation function
])

#compile the model
model.compile(optimizer='adam',loss='mean_absolute_error',metrics=['mae'])
model.summary()

c:\Users\himan\miniconda3\envs\annenv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [38]:
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime
log_dir='regressionlogs/fit'+datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback=TensorBoard(log_dir=log_dir,histogram_freq=1)

In [39]:
early_stoping_callback=EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True)

In [40]:
historyy=model.fit(
    x_train,y_train,
    validation_data=(x_test,y_test),
    epochs=100,
    callbacks=[tensorboard_callback,early_stoping_callback]
    )

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 100386.2500 - mae: 100386.2500 - val_loss: 98554.8906 - val_mae: 98554.8906
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 99800.5625 - mae: 99800.5625 - val_loss: 97380.8906 - val_mae: 97380.8906
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 97770.2266 - mae: 97770.2266 - val_loss: 94392.0859 - val_mae: 94392.0859
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 93732.9922 - mae: 93732.9922 - val_loss: 89281.2344 - val_mae: 89281.2344
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 87692.7500 - mae: 87692.7500 - val_loss: 82456.6016 - val_mae: 82456.6016
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 80118.4453 - mae: 80118.4453 - val_loss: 74613.6875 - val_mae: 74613.6875
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 72011.1719 - mae: 72011.1719 - val_loss: 67043.6016 - val_mae: 67043.6016
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 64499.2461 - mae: 64499.2461 - val_loss: 60622.5234 - val_mae: 60622.5234
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 58550.7812 - mae: 58550.7812 - val_loss: 55958.5352 - val_mae: 55958.5352
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 54617.1445 - mae: 54617.1445 - val_loss: 53183.0703 - val_mae: 53183.0703
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 52351.2578 - mae: 52351.2578 - val_loss: 51926.1094 - val_mae: 51926.1094
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 51243.8867 - mae: 51243.8867 - val_loss: 51387.2773 - val_mae: 51387.2773
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 50749.5938 - mae: 50749.5938 - val_loss: 51186.8984 - val_mae: 51186.8984
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 50513.9414 - mae: 50513.9414 - val_loss: 51080.7578 - val_mae: 51080.7578
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 50386.1602 - mae: 50386.1602 - val_loss: 51013.1562 - val_mae: 51013.1562
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 50296.9258 - mae: 50296.9258 - val_loss: 50952.7578 - val_mae: 50952.7578
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 50233.8125 - mae: 50233.8125 - val_loss: 50893.0273 - val_mae: 50893.0273
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 50180.4766 - mae: 50180.4766 - val_loss: 50860.6445 - val_mae: 50860.6445
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 50129.4336 - mae: 50129.4336 - val_loss: 50805.7227 - val_mae: 50805.7227
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 50085.1484 - mae: 50085.1484 - val_loss: 50771.7422 - val_mae: 50771.7422
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 50049.7852 - mae: 50049.7852 - val_loss: 50739.6055 - val_mae: 50739.6055
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 50010.6172 - mae: 50010.6172 - val_loss: 50700.6484 - val_mae: 50700.6484
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49977.5586 - mae: 49977.5586 - val_loss: 50670.2891 - val_mae: 50670.2891
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49947.7930 - mae: 49947.7930 - val_loss: 50643.9883 - val_mae: 50643.9883
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49919.0508 - mae: 49919.0508 - val_loss: 50609.5078 - val_mae: 50609.5078
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49890.1562 - mae: 49890.1562 - val_loss: 50596.2773 - val_mae: 50596.2773
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49862.8633 - mae: 49862.8633 - val_loss: 50565.9062 - val_mae: 50565.9062
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49837.8906 - mae: 49837.8906 - val_loss: 50543.6055 - val_mae: 50543.6055
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49817.3945 - mae: 49817.3945 - val_loss: 50530.0781 - val_mae: 50530.0781
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49794.2812 - mae: 49794.2812 - val_loss: 50524.0977 - val_mae: 50524.0977
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49770.6094 - mae: 49770.6094 - val_loss: 50501.1953 - val_mae: 50501.1953
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49750.7031 - mae: 49750.7031 - val_loss: 50475.0312 - val_mae: 50475.0312
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49735.7812 - mae: 49735.7812 - val_loss: 50456.3867 - val_mae: 50456.3867
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49717.6992 - mae: 49717.6992 - val_loss: 50447.2852 - val_mae: 50447.2852
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49703.2383 - mae: 49703.2383 - val_loss: 50438.3789 - val_mae: 50438.3789
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49687.8008 - mae: 49687.8008 - val_loss: 50425.0938 - val_mae: 50425.0938
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49674.4648 - mae: 49674.4648 - val_loss: 50425.2773 - val_mae: 50425.2773
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49656.0195 - mae: 49656.0195 - val_loss: 50422.5703 - val_mae: 50422.5703
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49645.9609 - mae: 49645.9609 - val_loss: 50410.1836 - val_mae: 50410.1836
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49632.1641 - mae: 49632.1641 - val_loss: 50403.1484 - val_mae: 50403.1484
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49622.0156 - mae: 49622.0156 - val_loss: 50391.0547 - val_mae: 50391.0547
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49608.8438 - mae: 49608.8438 - val_loss: 50392.4961 - val_mae: 50392.4961
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49598.8789 - mae: 49598.8789 - val_loss: 50392.0625 - val_mae: 50392.0625
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49588.6172 - mae: 49588.6172 - val_loss: 50381.0977 - val_mae: 50381.0977
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49581.6875 - mae: 49581.6875 - val_loss: 50391.3711 - val_mae: 50391.3711
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49575.9492 - mae: 49575.9492 - val_loss: 50385.0156 - val_mae: 50385.0156
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49567.7578 - mae: 49567.7578 - val_loss: 50389.6211 - val_mae: 50389.6211
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49556.1055 - mae: 49556.1055 - val_loss: 50383.3281 - val_mae: 50383.3281
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49549.0898 - mae: 49549.0898 - val_loss: 50382.3711 - val_mae: 50382.3711
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49542.0352 - mae: 49542.0352 - val_loss: 50386.6836 - val_mae: 50386.6836
Epoch 51/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49534.1641 - mae: 49534.1641 - val_loss: 50381.1484 - val_mae: 50381.1484
Epoch 52/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49529.6523 - mae: 49529.6523 - val_loss: 50382.8789 - val_mae: 50382.8789
Epoch 53/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49521.5977 - mae: 49521.5977 - val_loss: 50378.7070 - val_mae: 50378.7070
Epoch 54/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49511.1406 - mae: 49511.1406 - val_loss: 50378.4258 - val_mae: 50378.4258
Epoch 55/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49505.9805 - mae: 49505.9805 - val_loss: 50380.3828 - val_mae: 50380.3828
Epoch 56/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49500.2617 - mae: 49500.2617 - val_loss: 50374.3750 - val_mae: 50374.3750
Epoch 57/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49492.8242 - mae: 49492.8242 - val_loss: 50376.2266 - val_mae: 50376.2266
Epoch 58/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49490.7422 - mae: 49490.7422 - val_loss: 50371.3320 - val_mae: 50371.3320
Epoch 59/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49481.0586 - mae: 49481.0586 - val_loss: 50375.9492 - val_mae: 50375.9492
Epoch 60/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49472.6094 - mae: 49472.6094 - val_loss: 50371.0781 - val_mae: 50371.0781
Epoch 61/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49467.3125 - mae: 49467.3125 - val_loss: 50370.9336 - val_mae: 50370.9336
Epoch 62/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49461.9844 - mae: 49461.9844 - val_loss: 50374.1016 - val_mae: 50374.1016
Epoch 63/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49457.4102 - mae: 49457.4102 - val_loss: 50376.3320 - val_mae: 50376.3320
Epoch 64/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49455.1484 - mae: 49455.1484 - val_loss: 50375.8672 - val_mae: 50375.8672
Epoch 65/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49447.4961 - mae: 49447.4961 - val_loss: 50368.3008 - val_mae: 50368.3008
Epoch 66/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49444.2930 - mae: 49444.2930 - val_loss: 50377.0703 - val_mae: 50377.0703
Epoch 67/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49439.9453 - mae: 49439.9453 - val_loss: 50372.5234 - val_mae: 50372.5234
Epoch 68/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49431.8867 - mae: 49431.8867 - val_loss: 50372.4531 - val_mae: 50372.4531
Epoch 69/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49429.1523 - mae: 49429.1523 - val_loss: 50371.1289 - val_mae: 50371.1289
Epoch 70/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49424.5078 - mae: 49424.5078 - val_loss: 50369.8320 - val_mae: 50369.8320
Epoch 71/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49419.1562 - mae: 49419.1562 - val_loss: 50379.4570 - val_mae: 50379.4570
Epoch 72/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49415.4844 - mae: 49415.4844 - val_loss: 50376.3984 - val_mae: 50376.3984
Epoch 73/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49410.8320 - mae: 49410.8320 - val_loss: 50376.9531 - val_mae: 50376.9531
Epoch 74/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 49407.7148 - mae: 49407.7148 - val_loss: 50376.5195 - val_mae: 50376.5195
Epoch 75/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49402.0703 - mae: 49402.0703 - val_loss: 50384.2773 - val_mae: 50384.2773

In [41]:
%load_ext tensorboard

In [43]:
#Tensoboard setup (web server)
import subprocess

process = subprocess.Popen([
    "python",
    "-m",
    "tensorboard.main",
    "--logdir",
    r"D:\Ann project\model\regressionlogs\fit20260921-133151",
    "--port",
    "6008"
])

In [44]:
#saving the trained model
model.save('model_reg.keras')