### Prediction with ANN model

In [1]:
#Required Libraries
import tensorflow as tf
from tensorflow.keras.models import load_model
import pickle
import pandas as pd
import numpy as np

In [2]:
#ANN model
model=load_model('model.keras')

#Encoded file 
with open('le_gen.pkl','rb') as file:
    le_gen=pickle.load(file)

with open('oneHot_geo.pkl','rb') as file:
    oneHot_geo=pickle.load(file)

#scaled file
with open('scaler.pkl','rb') as file:
    scaler=pickle.load(file)

In [3]:
#Setting up the input data
input_data={
'CreditScore':600,
'Gender':'Male',
 'Age':40, 
 'Tenure': 3,
'Balance':60000,
'NumOfProducts':2,
'HasCrCard':1,
'IsActiveMember':1,
'EstimatedSalary':50000,
'Geography':'France'
}

In [4]:
#converting the data to dataframe
input_df=pd.DataFrame([input_data])
input_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography
0,600,Male,40,3,60000,2,1,1,50000,France

In [5]:
# OneHot encoding 
geo_encoded=oneHot_geo.transform([[input_data['Geography']]]).toarray()
geo_encoded_df=pd.DataFrame(geo_encoded,columns=oneHot_geo.get_feature_names_out(['Geography']))

c:\Users\himan\miniconda3\envs\annenv\Lib\site-packages\sklearn\utils\validation.py:2830: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

In [6]:
# label encoding 
input_df['Gender']=le_gen.transform([input_df['Gender']])

c:\Users\himan\miniconda3\envs\annenv\Lib\site-packages\sklearn\preprocessing\_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

In [7]:
# Concatination of onehot encoded data
input_df=pd.concat([input_df.drop('Geography',axis=1),geo_encoded_df],axis=1)

In [8]:
input_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,1,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [9]:
# scale the input data
input_scaler=scaler.transform(input_df)
input_scaler

array([[-0.53598516,  0.91324755,  0.10479359, -0.69539349, -0.25781119,
         0.80843615,  0.64920267,  0.97481699, -0.87683221,  1.00150113,
        -0.57946723, -0.57638802]])

In [10]:
prediction=model.predict(input_scaler)
prediction

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

array([[0.02708971]], dtype=float32)

In [11]:
prediction_proba=prediction[0][0]

In [12]:
prediction_proba

np.float32(0.027089706)

In [13]:
if prediction_proba > 0.5:
    print('The customer is likely to churn.')
else:
    print('The customer is not likely to churn.')

The customer is not likely to churn.